### ISSUE TITLE
Recommended to replace the native library

### ISSUE THREAD

**Issue by b23r0** [extremeheat/node-raknet-native#10]
In actual use, I found that the raknet implementation of the fb-raknet (c++) version has problems such as a large number of thread leaks. 

```
top -p [pid] -H
```

![1649411856(1)](https://user-images.githubusercontent.com/35518985/162413064-2cd7e6f0-adfb-4a0a-85c3-c5c13062aa41.jpg)

Since this native code has not been maintained for many years, I suggest to consider replacing it with a new raknet I implemented in rust, which is still compatible with minecraft.

https://github.com/b23r0/rust-raknet

It has proven stable in production environments.

**Comment by extremeheat** [comment]
Hi,

Sorry for no reply here. This is something that can be explored, possibly in a new package. I just have not had the time to look into this thus far.

**Comment by b23r0** [comment]
> Hi,
> 
> Sorry for no reply here. This is something that can be explored, possibly in a new package. I just have not had the time to look into this thus far.

It doesn't matter, I used rust to re-develop and bind nodejs, you can take a look if you are interested.

https://github.com/b23r0/raknet-node
