### ISSUE TITLE
Installation on Linux failed

### ISSUE THREAD

**Issue by LarryTLlama** [extremeheat/node-raknet-native#13]
Hey, having problems running raknet-native on a Rapberry Pi running Linux today:

Error log:
`/home/pi/Desktop/raknet/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/Desktop/raknet/node_modules/raknet-native/build/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/build/Debug/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/build/Release/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/out/Debug/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/Debug/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/out/Release/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/Release/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/build/default/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/compiled/18.2.0/linux/arm/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node
 → /home/pi/Desktop/raknet/node_modules/raknet-native/lib/binding/node-v108-linux-arm/node-raknet.node
    at bindings (/home/pi/Desktop/raknet/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/pi/Desktop/raknet/node_modules/raknet-native/binding.js:30:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/Desktop/raknet/node_modules/raknet-native/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  tries: [
    '/home/pi/Desktop/raknet/node_modules/raknet-native/build/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/build/Debug/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/build/Release/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/out/Debug/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/Debug/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/out/Release/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/Release/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/build/default/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/compiled/18.2.0/linux/arm/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node',
    '/home/pi/Desktop/raknet/node_modules/raknet-native/lib/binding/node-v108-linux-arm/node-raknet.node'
  ]
}

Node.js v18.2.0
`
Also ran this on Node V12.0.0 (on another machine) and no luck
Works great on a Windows 10 device though!

Found #4 but was not sure if that related to this. Is there any short-term fixes for this yet?
Thanks, Larry.

**Comment by Kaaaaii** [comment]
agree, dont work on pi pls fix

**Comment by extremeheat** [comment]
Please provide the entire install log. There is not enough information here to deduce the problem.

**Comment by LarryTLlama** [comment]
> Please provide the entire install log. There is not enough information here to deduce the problem.

NPM Ran into some errors on my side when installing. Ended up having to clone the repo and use it that way, hence the above (in-full) error log. Finally got my side fixed, so here's the error log from installing with `npm i raknet-native`, somewhat similar to the above with an error with some sort of bindings file:

[raknet-native-log.txt](https://github.com/extremeheat/node-raknet-native/files/9188919/raknet-native-log.txt)

**Comment by extremeheat** [comment]
> npm ERR! ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.

This error is due to missing CMake. You need to install it on your system, google how to do it with your system's package manager
