### ISSUE TITLE
raknet-native library not found

### ISSUE THREAD

**Issue by Pete9xi** [extremeheat/node-raknet-native#18]
Hi Im trying to run a script on ARMv7 Processor is this supported with raknet and the bedrock-protocol?

[raknet] raknet-native library not found, defaulting to jsp-raknet. Correct the "raknetBackend" option to avoid this error. Error: Could not locate the bindings file. Tried:
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/build/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/build/Debug/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/build/Release/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/out/Debug/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/Debug/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/out/Release/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/Release/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/build/default/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/compiled/18.15.0/linux/arm/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/addon-build/release/install-root/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/addon-build/debug/install-root/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/addon-build/default/install-root/node-raknet.node
 → /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native/lib/binding/node-v108-linux-arm/node-raknet.node

**Comment by Pete9xi** [comment]
i have also pulled more data from the log file when trying to install raknet-native, hope this helps debug the error

54 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1168ms
55 timing auditReport:getReport Completed in 1250ms
56 silly audit report {}
57 timing auditReport:init Completed in 0ms
58 timing reify:audit Completed in 1263ms
59 timing reifyNode:node_modules/raknet-native Completed in 2730ms
60 timing reify:unpack Completed in 2733ms
61 timing reify:unretire Completed in 2ms
62 timing build:queue Completed in 7ms
63 info run raknet-native@1.2.2 install node_modules/raknet-native node buildChecks.js
64 info run raknet-native@1.2.2 install { code: 127, signal: null }
65 timing reify:rollback:createSparse Completed in 335ms
66 timing reify:rollback:retireShallow Completed in 6ms
67 timing command:install Completed in 9575ms
68 verbose stack Error: command failed
68 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
68 verbose stack     at ChildProcess.emit (node:events:513:28)
68 verbose stack     at maybeClose (node:internal/child_process:1091:16)
68 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
69 verbose pkgid raknet-native@1.2.2
70 verbose cwd /home/ubuntu/sambashare/Discord Bot AnarchyXI
71 verbose Linux 5.15.0-1025-raspi
72 verbose node v18.15.0
73 verbose npm  v9.5.0
74 error code 127
75 error path /home/ubuntu/sambashare/Discord Bot AnarchyXI/node_modules/raknet-native
76 error command failed
77 error command sh -c node buildChecks.js
78 error /home/ubuntu/node_modules/.bin/../node/bin/node: 1: This: not found
79 verbose exit 127
80 timing npm Completed in 10145ms
81 verbose unfinished npm timer reify 1682120706889
82 verbose unfinished npm timer reify:build 1682120715916
83 verbose unfinished npm timer build 1682120715922
84 verbose unfinished npm timer build:deps 1682120715923
85 verbose unfinished npm timer build:run:install 1682120715935
86 verbose unfinished npm timer build:run:install:node_modules/raknet-native 1682120715938
87 verbose code 127
88 error A complete log of this run can be found in:
88 error     /home/ubuntu/.npm/_logs/2023-04-21T23_45_06_329Z-debug-0.log

**Comment by extremeheat** [comment]
Can you provide the log when you do `npm install raknet-native` ? You could be missing CMake or something. You can also consisder using https://github.com/b23r0/raknet-node if that works on your hardware.

**Comment by Pete9xi** [comment]
hi extremeheat i have resolved this by completely deleting node_modules and re building it
